### ISSUE TITLE
Having trouble fetching the request object

### ISSUE THREAD

**Issue by mlambley** [Rareloop/router#8]
Good day, I'm just trying to fetch my request object in the callable:

```php
$router->post('/api/customers', function(RequestInterface $request) {
   //$request->getParsedBody() etc
});
```

I'm aware of Responsable, but that would require me to create a separate class for each route. Could you provide example code which allows me to fetch the request object, or at least the posted body data, in the closure? Thanks.

**Comment by mlambley** [comment]
I ended up using League's router, but I'd still appreciate any advice you can give.

**Comment by joelambert** [comment]
Hi Mark,

Did you setup your `Router` instance with a compatible DI container as that is required to inject params into a closure? 

https://github.com/Rareloop/router#using-with-a-dependency-injection-container

```
$container = new Container();

$testServiceInstance = new TestService();
$container->set(TestService::class, $testServiceInstance);

$router = new Router($container);

$router->get('/my/route', function (TestService $service) {
    // $service is now the same object as $testServiceInstance
});
```

**Comment by mlambley** [comment]
I used League's container. Example code below. Please tell me what I'm doing wrong.

```php
<?php
require_once 'vendor/autoload.php';

$stream = fopen('php://temp', 'r+');
fwrite($stream, '{"id":5}');
fseek($stream, 0);
$body = new \Laminas\Diactoros\Stream($stream);

$serverRequest = new \Laminas\Diactoros\ServerRequest(
    [],
    [],
    '/api/customers',
    'post',
    $body,
    [],
    [],
    [],
    json_decode('{"id":5}'),
    '1.1'
);

$container = new \League\Container\Container();
$router = new \Rareloop\Router\Router($container);

$router->post('/api/customers', function(\Psr\Http\Message\ServerRequestInterface $request) {
    var_dump($request->getParsedBody());
});

$response = $router->match($serverRequest);
```

Gives error:

```
PHP Fatal error:  Uncaught Error: Cannot instantiate interface Psr\Http\Message\ServerRequestInterface in vendor\rareloop\router\src\TypeHintRequestResolver.php:56
Stack trace:
#0 vendor\rareloop\router\src\TypeHintRequestResolver.php(56): ReflectionClass->newInstance(Array, Array, Object(Laminas\Diactoros\Uri), 'post', Object(Laminas\Diactoros\Stream), Array, Array, Array, Object(stdClass), '1.1')
#1 vendor\rareloop\router\src\TypeHintRequestResolver.php(37): Rareloop\Router\TypeHintRequestResolver->createRequestOfType(Object(ReflectionClass))
#2 vendor\php-di\invoker\src\ParameterResolver\ResolverChain.php(37): Rareloop\Router\TypeHintRequestResolver->getParameters(Object(ReflectionFunction), Array, Array)
#3 vendor\php-di\invoker\src\Invoker.php(65): Invoker\ParameterResolver\ResolverChain->getParameters(Object(ReflectionFunction), Array, Array)
#4 vendor\rareloop\router\src\RouteAction.php(56): Invoker\Invoker->call( in vendor\rareloop\router\src\TypeHintRequestResolver.php on line 56

Fatal error: Uncaught Error: Cannot instantiate interface Psr\Http\Message\ServerRequestInterface in vendor\rareloop\router\src\TypeHintRequestResolver.php:56
Stack trace:
#0 vendor\rareloop\router\src\TypeHintRequestResolver.php(56): ReflectionClass->newInstance(Array, Array, Object(Laminas\Diactoros\Uri), 'post', Object(Laminas\Diactoros\Stream), Array, Array, Array, Object(stdClass), '1.1')
#1 vendor\rareloop\router\src\TypeHintRequestResolver.php(37): Rareloop\Router\TypeHintRequestResolver->createRequestOfType(Object(ReflectionClass))
#2 vendor\php-di\invoker\src\ParameterResolver\ResolverChain.php(37): Rareloop\Router\TypeHintRequestResolver->getParameters(Object(ReflectionFunction), Array, Array)
#3 vendor\php-di\invoker\src\Invoker.php(65): Invoker\ParameterResolver\ResolverChain->getParameters(Object(ReflectionFunction), Array, Array)
#4 vendor\rareloop\router\src\RouteAction.php(56): Invoker\Invoker->call( in vendor\rareloop\router\src\TypeHintRequestResolver.php on line 56
```

**Comment by joelambert** [comment]
I suspect that the container doesn't know what concrete implementation to use to resolve the `ServerRequestInterface`. I'm not familiar with the League container but it looks like you can add an alias to tell it what class to use for the interface https://container.thephpleague.com/3.x/#aliases

You could try that or instead try Type Hinting against a concrete Request implementation e.g. `Laminas\Diactoros\ServerRequest`?

**Comment by mlambley** [comment]
Typehinting `\Laminas\Diactoros\ServerRequest` did fix the problem. Thanks for the tip!
